services:
  couchdb:
    image: couchdb:3.3
    container_name: couchdb_vite
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: votaciones2024
    ports:
      - "5984:5984"
    volumes:
      - couchdb_vite_data:/opt/couchdb/data
    restart: unless-stopped

  vite:
    image: node:18-alpine
    container_name: vite_app
    working_dir: /app
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: development
    volumes:
      - .:/app
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    command: npm run dev
    depends_on:
      - couchdb
    restart: unless-stopped

volumes:
  couchdb_vite_data:
