# docker-compose.yml - Sin version (ya no es necesaria)
services:
  couchdb:
    image: couchdb:3.3
    container_name: votaciones_couchdb
    environment:
      - COUCHDB_USER=admin
      - COUCHDB_PASSWORD=admin123
    ports:
      - "5984:5984"
    volumes:
      - couchdb_data:/opt/couchdb/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5984/_up"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    container_name: votaciones_app
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_COUCHDB_URL=http://admin:admin123@couchdb:5984
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    depends_on:
      couchdb:
        condition: service_healthy
    volumes:
      - ./src:/app/src
      - ./public:/app/public
      - /app/node_modules
    restart: unless-stopped

volumes:
  couchdb_data: