services:
  couchdb:
    image: couchdb:3.3
    container_name: couch_simple
    environment:
      COUCHDB_USER: admin
      COUCHDB_PASSWORD: votaciones2024
    ports:
      - "5984:5984"
    volumes:
      - couch_data:/opt/couchdb/data

  react:
    image: node:18-alpine
    container_name: react_simple
    working_dir: /workspace
    ports:
      - "3000:3000"
    environment:
      HOST: 0.0.0.0
      GENERATE_SOURCEMAP: false
      CHOKIDAR_USEPOLLING: true
    volumes:
      - .:/workspace
    command: sh -c "npm install --legacy-peer-deps && npm start"

volumes:
  couch_data:
